version: '3.8'

services:
  frontend:
    image: portfolio-fe
    container_name: portfolio-fe
    build:
      context: ./portfolio-fe
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    env_file:
      - .env.prod
    depends_on:
      - backend
    restart: always

  backend:
    image: portfolio-be
    container_name: portfolio-be
    build: 
      context: ./portfolio-be
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@localhost:27017/ --quiet
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongodb_data: 
  